// ============================================================
// MaatWork CRM — Route Tree (Generated placeholder)
// ============================================================
// NOTE: This file is auto-generated by TanStack Router.
// This is a placeholder for initial development.
// Run `pnpm dev` to regenerate from actual route files.
// ============================================================

import { createRootRoute, createRoute, createRouter } from "@tanstack/react-router";

// Placeholder — will be replaced by code generation on `pnpm dev`
export const routeTree = {} as any;
