/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiSimpleTestRouteImport } from './routes/api/simple-test'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTrainingRouteImport } from './routes/_app/training'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSegmentsRouteImport } from './routes/_app/segments'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppDriveRouteImport } from './routes/_app/drive'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCareerPlanRouteImport } from './routes/_app/career-plan'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as ApiTestWildcardSplatRouteImport } from './routes/api/test-wildcard/$'
import { Route as ApiDebugSessionRouteImport } from './routes/api/debug/session'
import { Route as ApiAuthTestRouteImport } from './routes/api/auth/test'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as ApiGoogleDriveFilesRouteImport } from './routes/api/google/drive/files'
import { Route as ApiGoogleCalendarEventsRouteImport } from './routes/api/google/calendar/events'
import { Route as ApiAuthCallbackSplatRouteImport } from './routes/api/auth/callback/$'
import { Route as ApiGoogleCalendarEventsEventIdRouteImport } from './routes/api/google/calendar/events/$eventId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimpleTestRoute = ApiSimpleTestRouteImport.update({
  id: '/api/simple-test',
  path: '/api/simple-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerPlanRoute = AppCareerPlanRouteImport.update({
  id: '/career-plan',
  path: '/career-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTestWildcardSplatRoute = ApiTestWildcardSplatRouteImport.update({
  id: '/api/test-wildcard/$',
  path: '/api/test-wildcard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSessionRoute = ApiDebugSessionRouteImport.update({
  id: '/api/debug/session',
  path: '/api/debug/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestRoute = ApiAuthTestRouteImport.update({
  id: '/api/auth/test',
  path: '/api/auth/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const ApiGoogleDriveFilesRoute = ApiGoogleDriveFilesRouteImport.update({
  id: '/api/google/drive/files',
  path: '/api/google/drive/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarEventsRoute = ApiGoogleCalendarEventsRouteImport.update({
  id: '/api/google/calendar/events',
  path: '/api/google/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackSplatRoute = ApiAuthCallbackSplatRouteImport.update({
  id: '/api/auth/callback/$',
  path: '/api/auth/callback/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarEventsEventIdRoute =
  ApiGoogleCalendarEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => ApiGoogleCalendarEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AppAutomationsRoute
  '/calendar': typeof AppCalendarRoute
  '/career-plan': typeof AppCareerPlanRoute
  '/dashboard': typeof AppDashboardRoute
  '/drive': typeof AppDriveRoute
  '/feedback': typeof AppFeedbackRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/segments': typeof AppSegmentsRoute
  '/tasks': typeof AppTasksRoute
  '/training': typeof AppTrainingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/simple-test': typeof ApiSimpleTestRoute
  '/api/test': typeof ApiTestRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test': typeof ApiAuthTestRoute
  '/api/debug/session': typeof ApiDebugSessionRoute
  '/api/test-wildcard/$': typeof ApiTestWildcardSplatRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/api/auth/callback/$': typeof ApiAuthCallbackSplatRoute
  '/api/google/calendar/events': typeof ApiGoogleCalendarEventsRouteWithChildren
  '/api/google/drive/files': typeof ApiGoogleDriveFilesRoute
  '/api/google/calendar/events/$eventId': typeof ApiGoogleCalendarEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AppAutomationsRoute
  '/calendar': typeof AppCalendarRoute
  '/career-plan': typeof AppCareerPlanRoute
  '/dashboard': typeof AppDashboardRoute
  '/drive': typeof AppDriveRoute
  '/feedback': typeof AppFeedbackRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/resources': typeof AppResourcesRoute
  '/segments': typeof AppSegmentsRoute
  '/tasks': typeof AppTasksRoute
  '/training': typeof AppTrainingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/simple-test': typeof ApiSimpleTestRoute
  '/api/test': typeof ApiTestRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test': typeof ApiAuthTestRoute
  '/api/debug/session': typeof ApiDebugSessionRoute
  '/api/test-wildcard/$': typeof ApiTestWildcardSplatRoute
  '/contacts': typeof AppContactsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/api/auth/callback/$': typeof ApiAuthCallbackSplatRoute
  '/api/google/calendar/events': typeof ApiGoogleCalendarEventsRouteWithChildren
  '/api/google/drive/files': typeof ApiGoogleDriveFilesRoute
  '/api/google/calendar/events/$eventId': typeof ApiGoogleCalendarEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/career-plan': typeof AppCareerPlanRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drive': typeof AppDriveRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/segments': typeof AppSegmentsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/training': typeof AppTrainingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/simple-test': typeof ApiSimpleTestRoute
  '/api/test': typeof ApiTestRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/test': typeof ApiAuthTestRoute
  '/api/debug/session': typeof ApiDebugSessionRoute
  '/api/test-wildcard/$': typeof ApiTestWildcardSplatRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/api/auth/callback/$': typeof ApiAuthCallbackSplatRoute
  '/api/google/calendar/events': typeof ApiGoogleCalendarEventsRouteWithChildren
  '/api/google/drive/files': typeof ApiGoogleDriveFilesRoute
  '/api/google/calendar/events/$eventId': typeof ApiGoogleCalendarEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/calendar'
    | '/career-plan'
    | '/dashboard'
    | '/drive'
    | '/feedback'
    | '/pipeline'
    | '/reports'
    | '/resources'
    | '/segments'
    | '/tasks'
    | '/training'
    | '/login'
    | '/register'
    | '/api/simple-test'
    | '/api/test'
    | '/settings/audit'
    | '/api/auth/$'
    | '/api/auth/test'
    | '/api/debug/session'
    | '/api/test-wildcard/$'
    | '/contacts/'
    | '/settings/'
    | '/teams/'
    | '/api/auth/callback/$'
    | '/api/google/calendar/events'
    | '/api/google/drive/files'
    | '/api/google/calendar/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/calendar'
    | '/career-plan'
    | '/dashboard'
    | '/drive'
    | '/feedback'
    | '/pipeline'
    | '/reports'
    | '/resources'
    | '/segments'
    | '/tasks'
    | '/training'
    | '/login'
    | '/register'
    | '/api/simple-test'
    | '/api/test'
    | '/settings/audit'
    | '/api/auth/$'
    | '/api/auth/test'
    | '/api/debug/session'
    | '/api/test-wildcard/$'
    | '/contacts'
    | '/settings'
    | '/teams'
    | '/api/auth/callback/$'
    | '/api/google/calendar/events'
    | '/api/google/drive/files'
    | '/api/google/calendar/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/automations'
    | '/_app/calendar'
    | '/_app/career-plan'
    | '/_app/dashboard'
    | '/_app/drive'
    | '/_app/feedback'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/resources'
    | '/_app/segments'
    | '/_app/tasks'
    | '/_app/training'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/simple-test'
    | '/api/test'
    | '/_app/settings/audit'
    | '/api/auth/$'
    | '/api/auth/test'
    | '/api/debug/session'
    | '/api/test-wildcard/$'
    | '/_app/contacts/'
    | '/_app/settings/'
    | '/_app/teams/'
    | '/api/auth/callback/$'
    | '/api/google/calendar/events'
    | '/api/google/drive/files'
    | '/api/google/calendar/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiSimpleTestRoute: typeof ApiSimpleTestRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthTestRoute: typeof ApiAuthTestRoute
  ApiDebugSessionRoute: typeof ApiDebugSessionRoute
  ApiTestWildcardSplatRoute: typeof ApiTestWildcardSplatRoute
  ApiAuthCallbackSplatRoute: typeof ApiAuthCallbackSplatRoute
  ApiGoogleCalendarEventsRoute: typeof ApiGoogleCalendarEventsRouteWithChildren
  ApiGoogleDriveFilesRoute: typeof ApiGoogleDriveFilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simple-test': {
      id: '/api/simple-test'
      path: '/api/simple-test'
      fullPath: '/api/simple-test'
      preLoaderRoute: typeof ApiSimpleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments': {
      id: '/_app/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive': {
      id: '/_app/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career-plan': {
      id: '/_app/career-plan'
      path: '/career-plan'
      fullPath: '/career-plan'
      preLoaderRoute: typeof AppCareerPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/test-wildcard/$': {
      id: '/api/test-wildcard/$'
      path: '/api/test-wildcard/$'
      fullPath: '/api/test-wildcard/$'
      preLoaderRoute: typeof ApiTestWildcardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/session': {
      id: '/api/debug/session'
      path: '/api/debug/session'
      fullPath: '/api/debug/session'
      preLoaderRoute: typeof ApiDebugSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/test': {
      id: '/api/auth/test'
      path: '/api/auth/test'
      fullPath: '/api/auth/test'
      preLoaderRoute: typeof ApiAuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/google/drive/files': {
      id: '/api/google/drive/files'
      path: '/api/google/drive/files'
      fullPath: '/api/google/drive/files'
      preLoaderRoute: typeof ApiGoogleDriveFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/calendar/events': {
      id: '/api/google/calendar/events'
      path: '/api/google/calendar/events'
      fullPath: '/api/google/calendar/events'
      preLoaderRoute: typeof ApiGoogleCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/$': {
      id: '/api/auth/callback/$'
      path: '/api/auth/callback/$'
      fullPath: '/api/auth/callback/$'
      preLoaderRoute: typeof ApiAuthCallbackSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/calendar/events/$eventId': {
      id: '/api/google/calendar/events/$eventId'
      path: '/$eventId'
      fullPath: '/api/google/calendar/events/$eventId'
      preLoaderRoute: typeof ApiGoogleCalendarEventsEventIdRouteImport
      parentRoute: typeof ApiGoogleCalendarEventsRoute
    }
  }
}

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCareerPlanRoute: typeof AppCareerPlanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriveRoute: typeof AppDriveRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSegmentsRoute: typeof AppSegmentsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCareerPlanRoute: AppCareerPlanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriveRoute: AppDriveRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSegmentsRoute: AppSegmentsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiGoogleCalendarEventsRouteChildren {
  ApiGoogleCalendarEventsEventIdRoute: typeof ApiGoogleCalendarEventsEventIdRoute
}

const ApiGoogleCalendarEventsRouteChildren: ApiGoogleCalendarEventsRouteChildren =
  {
    ApiGoogleCalendarEventsEventIdRoute: ApiGoogleCalendarEventsEventIdRoute,
  }

const ApiGoogleCalendarEventsRouteWithChildren =
  ApiGoogleCalendarEventsRoute._addFileChildren(
    ApiGoogleCalendarEventsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiSimpleTestRoute: ApiSimpleTestRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthTestRoute: ApiAuthTestRoute,
  ApiDebugSessionRoute: ApiDebugSessionRoute,
  ApiTestWildcardSplatRoute: ApiTestWildcardSplatRoute,
  ApiAuthCallbackSplatRoute: ApiAuthCallbackSplatRoute,
  ApiGoogleCalendarEventsRoute: ApiGoogleCalendarEventsRouteWithChildren,
  ApiGoogleDriveFilesRoute: ApiGoogleDriveFilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
